app/urls.py
from django.conf import settings
from django.urls import re_path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users import views as user_views
from notebook import views as notebook_views

urlpatterns = [
    re_path(r'^$', TemplateView.as_view(template_name='index.html')),
    re_path(r'^login', user_views.signin, name='login'),
    re_path(r'^signup', user_views.signup, name='signup'),
    re_path(r'^logout', auth_views.LogoutView, {'next_page': '/'}, name='logout'),

    re_path(r'^dashboard', user_views.dashboard, name='dashboard'),
    re_path(r'^account/edit', user_views.edit, name='edit-account'),
    re_path(r'^account', user_views.show, name='account'),
    re_path(r'^posts/new', notebook_views.create, name='new-post'),
    re_path(r'^edit-post/(?P<id>\d+)/$', notebook_views.edit, name='edit-post'),
    re_path(r'^posts/delete/(?P<id>\d+)/$', notebook_views.destroy, name='delete-post'),
    re_path(r'^(?P<username>\w+)/$', notebook_views.index, name='all-posts'),
    re_path(r'^(?P<username>\w+)/tags/(?P<name>.+?)/$', notebook_views.tag, name='tag'),

    re_path(r'^forgot-password/done', auth_views.PasswordResetDoneView),
    re_path(r'^forgot-password', auth_views.PasswordResetView, {'success_url': '/forgot-password/done'}, name="forgot-pw"),
    re_path(r'^password-reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView,
        {'post_reset_login' : False},
        name="pw-reset-confirm")
]

app/notebook/models.py
from django.db import models
from users.models import User

class Category(models.Model):
    name = models.CharField(max_length=255, default='', unique=True)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, through='Tag')
    title = models.CharField(max_length=255, default='')
    body = models.TextField(default='')
    date = models.DateTimeField()

class Tag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

app/notebook/forms.py
from django import forms
from datetime import datetime
from .models import *

class CreatePostForm(forms.Form):
    title = forms.CharField(label='Title',
                            widget=forms.TextInput(attrs={'class': 'input'}))
    body = forms.CharField(label='Post', 
                           widget=forms.Textarea(attrs={'class': 'textarea'}))
    categories = forms.CharField(label='Tags (separate by commas)',
                                 widget=forms.TextInput(attrs={'class': 'input',    
                                                               '@input': 'value => { tags = value }',
                                                               ':value': 'tags'}))
    
    def save(self, request):
        title = self.cleaned_data['title']
        body = self.cleaned_data['body']
        categories = self.cleaned_data['categories']
        post = Post.objects.create(user=request.user,
                           date=datetime.now(),
                           body=body,
                           title=title)

        for tag in categories.split(','):
            category = Category.objects.get_or_create(name=tag.strip())[0]
            Tag.objects.create(user=request.user, 
                               post=post, 
                               category=category)
        return post

class EditPostForm(forms.ModelForm):
    title = forms.CharField(label='Title',
                            widget=forms.TextInput(attrs={'class': 'input'}))
    body = forms.CharField(label='Post', 
                           widget=forms.Textarea(attrs={'class': 'textarea'}))
    categories = forms.CharField(label='Tags (separate by commas)',
                                 widget=forms.TextInput(attrs={'class': 'input',
                                                               'v-model': 'tags'}))
    
    class Meta: 
        model = Post
        fields = ('title', 'body', 'categories')

    def save(self, post):
        post.title = self.cleaned_data['title']
        post.body = self.cleaned_data['body']
        categories = self.cleaned_data['categories']
        post.save()
        post.tag_set.all().delete();
        for tag in categories.split(','):
            category = Category.objects.get_or_create(name=tag.strip())[0]
            Tag.objects.create(user=post.user, 
                                      post=post,
                                      category=category)
        return post

app/notebook/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import *
from .helpers import *

@login_required
def create(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            form.save(request)
            return redirect('/'+request.user.username)
    else:
        form = CreatePostForm()
    return render(request, 'notebook/new.html',
                  {'form': form, 'tags': tags(request.user), 'user': request.user})

def index(request, username):
    user = User.objects.get(username=username)
    posts = user.post_set.all().order_by('-date')
    # show 25 posts per page
    paginator = Paginator(posts, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,
                  'notebook/index.html',
                  {'posts': paginator, 'tags': tags(user), 'user': user})

@login_required
def edit(request, id):
    post = get_object_or_404(Post, pk=id)
    tags = [tag.category.name for tag in post.tag_set.all()]
    form = EditPostForm(request.POST or None,
                        instance=post,
                        initial={'categories': ','.join(tags) })
    if request.method == 'POST':
        if form.is_valid():
            form.save(post)
            return redirect('/'+request.user.username)
    return render(request,
                  'notebook/edit.html',
                  {'form': form, 'pk': id, 'user': request.user})

@login_required
def tag(request, username, name):
    user = get_object_or_404(User, username=username)
    category = get_object_or_404(Category, name=name)
    tagged_posts = request.user.tag_set.filter(category_id=category.id).order_by('-post_id')
    return render(request,
                  'tag/show.html',
                  {'tagged_posts': tagged_posts, 'category': category, 'tags':  tags(user), 'user': user})

@login_required
def destroy(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect('/'+request.user.username)

app/templates/notebook/edit.html
{% extends 'columns.html' %}
{% block title %} | Edit Post {% endblock %}

{% block page_name %}Edit Post{% endblock %}
{% block content %}
  <form method="POST" class="post-form">
    {% csrf_token %}
    <div class="field">
      <label for="id_title">Title</label>
      <div class="control">{{ form.title }}</div>
    </div>
    <div class="field">
      <label for="id_body">Post</label>
      <div class="control">{{ form.body }}</div>
    </div>

    <tag-form curr-tags="{{form.categories.value}}"></tag-form>

    <div class="field">
      <div class="control">
        <button type="submit" class="button is-info">Submit</button>
      </div>
    </div>
    
    <delete-btn inline-template>
      <div class="field">
        <div class="control">
          <a class="button is-danger" v-on:click="click">
            <span class="icon is-small"><i class="fa fa-trash"></i></span>
            <span>Delete</span>
          </a>

          <div v-if="clicked"> 
            <hr/>
            <p> Are you sure you want to delete this post?</p> 
            <a href="{% url 'delete-post' id=pk %}" class="button is-danger">Yes, delete this post</a>
            <a class="button is-info" v-on:click="clicked = false">No, I changed my mind</a>
        </div>
      </div>
    </delete-btn>
  </form>
{% endblock %}
  

app/templates/notebook/index.html
{% extends 'columns.html' %}
{% block title %} | All Posts{% endblock %}

{% block page_name %}Posts{% endblock %}
{% block content %}
  {% for post in posts %}
    <section class="section">
      <div class="columns">
        <div class="column">
          <h2 class="title">{{ post.title }}</h2> 
          <div class="subtitle">{{ post.date|date:"l F d Y H:i" }}</div>
        </div>
        <div class="column has-text-right-tablet">
          {% if request.user.is_authenticated and request.user == post.user  %}
            <a href="{% url 'edit-post' id=post.pk %}">
              <span class="icon"><i class="fa fa-laptop"></i></span> Edit
            </a>
          {% endif %}
        </div>
      </div>

      <hr/>

      <div>{{ post.body|safe|linebreaks|urlize }}</div>

      <hr/>
      <div class="tags">
        <span>Tags: </span>
        {% for tag in post.tag_set.all %}
          <span class="tag is-info">
            <a href="{% url 'tag' name=tag.category.name username=user.username %}">
              {{ tag.category.name }}
            </a>
          </span>
        {% endfor %}    
      </div>
    </section>
  {% endfor %}

  <div class="pagination">
    {% if posts.has_previous %}
      <a href="?page=1">1</a> <a href="?page={{ posts.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      page {{ posts.number }}
    </span>

    {% if posts.has_next %}
      <a href="?page={{ posts.next_page_number }}">next</a> <a href="?page={{ posts.paginator.num_pages }}">{{ posts.paginator.num_pages }}</a>
    {% endif %}
  </div>

{% endblock %}

app/templates/notebook/new.html
{% extends 'columns.html' %}
{% block title %} | New Post{% endblock %}

{% block page_name %}New Post{% endblock %}
{% block content %}
  <form method="POST" class="post-form">
    {% csrf_token %}
    <div class="field">         
      <label for="id_title">Title</label>
      <input id="id_title" class="input" name="title" required type="text">
    </div> 
    <div class="field" id="wysiwyg">
      <label for="id_body">Post</label> 
        <!--<textarea id="id_body" class="textarea" name="body" required>
        </textarea> -->
    </div>

    <editor inline-template="true">
      <textarea></textarea>
    </editor> 
    <tag-form>
      <div class="field">
        <label for="id_categories">Tags</label>
        <div class="tags">
          <span :class="{'tag is-info': tag != ''}" v-for="tag in this.processedTags">
            {{ tag }}
          </span>
        </div>
        <div class="control">
          <input id="id_categories" name="categories" type="text" class="input" v-model="tags"></input>
        </div>
      </div>
    </tag-form>

    <div class="field"> 
      <div class="control">
        <button type="submit" class="button is-info">Submit</button>
      </div>
    </div>
  </form>

{% endblock %}